sudo: required
services:
    - docker

before_install:
    - docker build -t tasso85/docker-react -f Dockerfile.dev .

script:
    - docker run tasso85/docker-react npm run test-coverage

deploy:
    provider: elasticbeanstalk
    region: 'us-west-2'
    app: 'docker-react'
    env: 'Docker-react-env'
    bucket_name: 'elasticbeanstalk-...'
    bucket_path: 'docker-react'
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_id:
        secure: "$AWS_SECRET_KEY"
