FROM node:alpine

WORKDIR /usr/app

COPY package.json .
RUN npm config set registry http://registry.npmjs.org/ && npm set progress=false && npm install --verbose

COPY . .

CMD ["npm", "run", "start"]